### ISSUE TITLE
i can't run this app

### ISSUE THREAD

**Issue by SrStick** [flathub/org.kde.ktouch#1]
This error occurs when I try to run:
![image](https://user-images.githubusercontent.com/28923770/66413382-a823d980-e9cd-11e9-8025-a64756cc89db.png)

OS: Linux Mint 19.2
DE: XFCE

**Comment by sebasgo** [comment]
There was bug in the Flathub build which broke KTouch if the Qt version on Flathub got updated. This fixed now. You need to update or resinstall the app, though.
