### ISSUE TITLE
accented words don't work

### ISSUE THREAD

**Issue by dinhokusanagi** [flathub/org.kde.ktouch#38]
Brazilian Portuguese: no way to type (ã) is not recognized at this stage of the application, there is no way to type or move to the next word
![Captura de tela de 2022-05-02 02-08-22](https://user-images.githubusercontent.com/43162113/166187159-923da76d-96a4-42d0-9614-103fc7c89425.png)
.

**Comment by tsdgeos** [comment]
This is a ktouch bug, not a ktouch-flatpak-package bug.

Please report it at bugs.kde.org
